### PR TITLE
Resolves #126: Supply page numbers and leaders for TOC

### LINKED ISSUE #126: Add page numbers on the TOC
I believe it should be possible to do it in JavaScript once Paged.js process is completed using `data-page-number` attribute.

### PR DESCRIPTION
**Pull request by djencks**
Note this requires the asciidoctor ruby changes in asciidoctor/asciidoctor#3670.  To test or view the results of the changes you need to build an asciidoctor.js including those changes, and install it in asciidoctor web pdf.

I didn't try to update the tests.  Even with the current asciidoctor.js, this adds page numbers which breaks visual comparison.

### CODE REVIEW

**Comment by Mogztter** [comment]
> Note this requires the asciidoctor ruby changes in asciidoctor/asciidoctor#3670. To test or view the results of the changes you need to build an asciidoctor.js including those changes, and install it in asciidoctor web pdf.

I think we should move forward and include this change in https://github.com/Mogztter/asciidoctor-pdf.js/blob/master/lib/document/document-converter.js
Do you want to give it a try?

> I didn't try to update the tests. Even with the current asciidoctor.js, this adds page numbers which breaks visual comparison.

You can check that you didn't break existing features and update the expected result using `DEBUG=true`.
This environment variable will preserve the generated PDF and you can then replace the files. See https://github.com/Mogztter/asciidoctor-pdf.js/pull/234

**Comment by djencks** [comment]
I can make a PR, but it might take a few days.  If you'd like to go ahead.

**Comment by Mogztter** [comment]
> I can make a PR, but it might take a few days. If you'd like to go ahead.

No that's fine, please do :+1:

**Comment by Mogztter** [comment]
@djencks I did quite a few changes but it seems to be working. Could you please check the expectations at https://github.com/djencks/asciidoctor-pdf.js/tree/issue-126-toc-pagenums-leaders/test/reference?

**Pull request merged**
