### PR TITLE
multi-lined download status

### PR DESCRIPTION
**Pull request by wh81752**
A PR for getting a multi-line download status: Expect to see something like this on downloading Chromium for supported platforms:

```console
Create directory structure
========
Downloading browser for mac      16%
Downloading browser for win      11%
Downloading browser for linux     7%
========
```

### CODE REVIEW

**Comment by wh81752** [comment]
@Mogztter - it basically works, still some fine tuning necessary => move cursor after download status-lines when finished OR -- perhaps better -- change PRE/POST condition in such a way, that cursor is at line after multi-line area. So that further logs to come will not overwrite status-line area.
Nonetheless, it basically works.

**Comment by wh81752** [comment]
Just a minor, while important, improvement:

```console
Create directory structure
===========================
Downloading browser for mac      16%
Downloading browser for win      11%
Downloading browser for linux     7%
===========================
^
```

TTY cursor is now a position indicated by caret (`^`) after each status line update. Whatever happens then, this modification ensures that follow-up log statements within the TTY are not overwriting the update-status block. One notable exception though would is of course `kill -9`, i.e. process killing.

**Comment by wh81752** [comment]
@Mogztter - this PR supersedes #488, however, there is no dependency on #488. So we can drop #488 in favor of this one.

**Comment by Mogztter** [comment]
Thanks, I will give it a try on my macOS laptop 🍎

**Comment by Mogztter** [comment]
It's working great but using a single line is probably less confusing (especially if you press <Enter> in the terminal):

```
Downloading browser [mac:  1%]
```

```
Downloading browsers [linux:  1%, mac:  1%, win:  1%]
```

**Comment by wh81752** [comment]
@Mogztter - proper single-line download status now, I guess ready to be merged with master. 

Btw, I wonder what the best GIT strategy now is. My approach would be:
1. rebase this branch on master (i.e. change git history is such a way as if this branch has been taken from current master), resolving potential merge conflicts while doing so.
2. Squash commit on this branch into one commit 
3. merge (done by you)

Is that the right way to do?

**Comment by Mogztter** [comment]
@wh81752 Yes, you can use an interactive rebase: `git rebase -i origin/master` (in this case, `origin` is `https://github.com/Mogztter/asciidoctor-web-pdf`) to squash all commits. You can also reword the first commit (while doing the rebase) to accurately describe what you did.
Then, force push on your branch. You need to force push because commits have changed.

If all goes well, you will have a pull request with a single commit.

**Comment by wh81752** [comment]
@Mogztter  - here we go,  ready to merge.###

**Comment by Mogztter** [comment]
Thanks and merged!

**Pull request merged**
